image:
  name: repo.ficld.ir/docker/compose:latest

before_script:
  - docker version
  - docker-compose version

Build-Stage:
  stage: Build-Stage
  script: |
    docker-compose down
    docker-compose build
