image:
  name: repo.ficld.ir/docker/compose:latest

before_script:
  - docker version
  - docker-compose version

Build-Stage:
  stage: build
  only:
    - develop
  script: |
    docker-compose down
    docker-compose build --no-cache --force-rm

Deploy-Stage:
  stage: deploy
  only:
    - develop
  script: |
    docker-compose up -d
